version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: examplestore-volume
        target: /app/data
volumes:
  examplestore-volume: